### ISSUE TITLE
Device mit Standard Full Topic (%prefix%/%topic%/) funktioniert nicht

### ISSUE THREAD

**Issue by hubecker** [klein0r/fhem-tasmota#1]
define spowtest TASMOTA_DEVICE sonoffpow %prefix%/%topic%/
bekommt nur 1 reading

transmission-state subscription acknowledged

cmd status 0 bringt keine readings

**Comment by JoschaMiddendorf** [comment]
Lasse mal den / am ende weg.
define spowtest TASMOTA_DEVICE sonoffpow %prefix%/%topic%/

**Comment by florie1706** [comment]
Habe jetzt ewig rumgespielt, bei mir geht es einwandfrei, allerdings nur mit dieser Vorgehensweise:

1. Im Sonoff selber über dessen Weboberfläche muss ein / am Ende des Fulltopics enthalten sein, also z.B. Sonoff/EG.wz/%topic%/%prefix%/

2. Bei Anlage in FHEM muss ich wiederum den / weglassen. Allerdings funktioniert das das Gerät bei Erstanlage noch nicht. Also daher zuerst das Gerät in FHEM anlegen. Danach das IODEV eintragen und speichern. Anschließend die "DEF" ändern, dass sie nicht Sonoff/EG.wz/%topic%/%prefix% ist, und abspeichern. Nun nochmal die DEF bearbeiten und auf das "richtige" Sonoff/EG.wz/%topic%/%prefix% (ohne /) stellen und abspeichern.

3. So erhalte ich direkt das Reading "lwt online". Danach "set cmd Status 0". Nun ist alles fertig und läuft bei mir so einewandfrei mit 3 verschiedenen Geräten (S20, Pow, Basic).

**Comment by Zwickor** [comment]
Ich kriege es nicht zu laufen. Habe exakt das gleiche Problem wie der TE. Habe es auch mit der Vorgehensweise von florie getestet. Kein Erfolg.

Was mich auch irritiert ist, dass bei Internals unter Full_Topic %prefix%/Basic_Lego/ steht. Sollte es nicht genau anders herum sein?

Über das klassische MQTT_DEVICE funktioniert alles hervorragend.

**Comment by klein0r** [comment]
Mh, eigentlich ist die ganze Magie, dass das die Platzhalter im String ausgetauscht werden. Wo diese stehen, sollte eigentlich komplett egal sein. Gibt es das Problem zur Zeit noch?

**Comment by MichaelGier** [comment]
Hey.
Ich habe ein Tasmota_Device für eine RF-Bridge engelegt. Leider erhalte ich keine Readings. Ich sehe jedoch über mein MQTT.fx das Befehle abgesetzt werden, denn CMD Status 0 zeigt mir auf MQTT.fx und der Konsole der Bridge alle Status-Anzeigen.
Hat vielleicht jemand eine Lösung ?

**Comment by Lizard00** [comment]
Ich habe leider zurzeit das selbe Problem. Keinerlei readings, der beschriebene Workaround funktioniert leider in meinem Fall nicht. Gibt es weitere mögliche Fehlerquellen?
Besten Dank die Hilfe und dieses Modul. 
![grafik](https://user-images.githubusercontent.com/27803548/56699656-b66b8b00-66f6-11e9-85a6-5874c99c1559.png)

**Comment by StefTank** [comment]
Das Problem hatte ich auch. Habe alle möglichen Kombinationen der Topics ausprobiert, hat alles nicht funktioniert. 
Das Internal READY stand immer auf 0.
Bei mir war die **Lösung** das Attribut IODev zu löschen und danach neu auf Mosquitto zu setzen.
READY ging sofort auf 1.

**Comment by it-dieter** [comment]
Das Problem habe ich auch und habe schon alles mögliche versucht. Internal Ready stand nach dem anlege auch auf 0, nach löschen des IODev dann auf 1. Doch die anderen Readings bleiben aus. Mit dem default angelegten on off kann ich das Device (Tasmota 6.5.1) schalten aber das war es auch schon. Die Version des TASMOTA_DEVICE ist aktuell.
Vielleicht hat jemand Abhilfe?
