### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by stifu69** [klein0r/fhem-tasmota#13]
Hallo Matthias
Zuerst einmal ein grosses Dankeschön für deine Arbeit, ich benutze dein Modul seit einigen Tagen für ein paar sonoff POW Einheiten auf fhem, bis Heute Morgen mehr oder weniger Problemlos. Nach einem Update von fhem kann ich jedoch die GUI vom fhem nur noch starten, wenn ich dein Modul auschecke, ansonsten kriege ich kein Web-Interface. Fehlermeldung im log:

PERL WARNING: TASMOTA::DEVICE::Expand() called too early to check prototype at ./FHEM/10_TASMOTA_DEVICE.pm line 266, <$fh> line 708.
2018.02.15 20:36:02 1: PERL WARNING: TASMOTA::DEVICE::Expand() called too early to check prototype at ./FHEM/10_TASMOTA_DEVICE.pm line 272, <$fh> line 708.
Undefined subroutine &TASMOTA::DEVICE::client_subscribe_topic called at ./FHEM/10_TASMOTA_DEVICE.pm line 123, <$fh> line 708.

Hast du vielleicht einen Idee, woran das liegen könnte?
Besten Dank.

Gruss Stephan

**Comment by klein0r** [comment]
Da weiß ich auch noch nicht so genau was die Zeilen sollen. Immerhin ist es eine Rekursion. Logisch, dass er die Routine vorher dann noch nicht kennt. Mal gucken wie man das lösen könnte... Sind ja eigentlich nur Warnings - bei mir führt das im Betrieb nicht zu Problemen.

**Comment by stifu69** [comment]
Hallo Matthias

Besten Dank, seit dem Update funktioniert alles Super, problemloses reboot ohne irgenwelche Nacharbeiten oder def einlesen.
Vielen Dank noch einmal!
Gruss Stephan

**Comment by klein0r** [comment]
Freut mich zu hören!

**Comment by stifu69** [comment]
Bin begeistert, woher das bei mir auch immer kam, jetzt ist es weg! :-)
