### ISSUE TITLE
ENERGIE Reading

### ISSUE THREAD

**Issue by MKeY1988x** [klein0r/fhem-tasmota#15]
Hallo Matthias,
Danke für das Modul. Du hast bei deinem letzten update ganz am Anfang deines Codes bei
`my @topics`
die deutsche Bezeichnung raus genommen
`stat/ERGEBNIS
tele/LAUFZEIT
tele/ENERGIE`
War das so beabsichtigt? Ich musste es wieder einbauen, damit ich Readings bekomme :)

**Comment by klein0r** [comment]
Ja, weil ab 5.10 oder so nur noch Englische Topics existieren. Finde ich einen sinnvollen Schritt und hatte mich daher an die letzte Version angepasst.
