### ISSUE TITLE
SONOFF DUAL/4CH POWER Command

### ISSUE THREAD

**Issue by hubecker** [klein0r/fhem-tasmota#2]
Bei SONOFF Dual oder Sonoff 4CH gibt es ja POWER1-4, dann sollte es auch ein set POWER1-4 ON/OFF geben. Bitte bei der  Entwicklung beachten.

**Comment by klein0r** [comment]
Ja dann fängt es sehr aufwendig zu werden. Wenn ich die Unterscheidung mache, muss ich auch alle anderen Dinge unterscheiden. Aktuell kann man das ja bereits über cmnd Power1 on usw. abdecken. Also es ist nicht unbedingt nötig dass als Standard-Befehle mit aufzunehmen.

Zumal mir das Gerät ja nur bei einem Power-Cycle mitteilt, was für ein Typ es überhaupt ist.
