### ISSUE TITLE
Fehler: no IODev provided

### ISSUE THREAD

**Issue by ManfredBrauchle** [klein0r/fhem-tasmota#20]
beim Anlegen eines TASMOTA_DEVICE bekomme ich leider nur die Fehlermeldung

> client device hash no IODev provided

FHEM 2.7 und Tasmota 6.1.1
hab ich irgendwelche Abhängigkeiten übersehen?

**Comment by perrycroft** [comment]
Habe bei mir das gleiche Problem, nachdem ich gerade mein FHEM neu aufgesetzt habe. Mosquitto ist installiert und in FHEM als MQTT Broker definiert. Ein MQTT_Device lässt sich problemlos definieren, erkennt das IODev und kann betrieben werden. 
Die Definition eines TASMOTA_DEVICE schlägt jedoch mit obiger Fehlermeldung fehl, so dass IODev nicht nachträglich gesetzt werden kann. 

Mit verbose 5 findet sich im Logfile:
```
2018.08.26 15:28:50 5: Cmd: >define Kugel TASMOTA_DEVICE Kugellampe Licht/%topic%/%prefix%/<
2018.08.26 15:28:50 5: Loading ./FHEM/10_TASMOTA_DEVICE.pm
2018.08.26 15:28:50 1: PERL WARNING: TASMOTA::DEVICE::Expand() called too early to check prototype at ./FHEM/10_TASMOTA_DEVICE.pm line 279.
2018.08.26 15:28:50 1: PERL WARNING: TASMOTA::DEVICE::Expand() called too early to check prototype at ./FHEM/10_TASMOTA_DEVICE.pm line 285.
2018.08.26 15:28:50 3: No I/O device found for Kugel
2018.08.26 15:28:50 1: client device hash no IODev provided
```

**Comment by o0shojo0o** [comment]
Ja bei mir selbiges ... :(

**Comment by ManfredBrauchle** [comment]
mit einem Trick scheint es zu funktionieren: das Device in der config definieren und dann wird es angelegt 
muss ich heute abend einmal testen

https://forum.fhem.de/index.php/topic,90499.msg832004.html#msg832004

**Comment by o0shojo0o** [comment]
Ja das geht, aber schön ist anders ;)

**Comment by ClashC** [comment]
Habe hier auch das Problem. 
Wird es dafür noch eine Lösung geben? Oder muss ich nach einer anderen MQTT Lösung suchen? :)

**Comment by o0shojo0o** [comment]
Ich nutze jetzt das neuen FHEM Modul MQTT2_Server https://forum.fhem.de/index.php?topic=90135.0
Lauf soweit gut :)

**Comment by mated77** [comment]
Kann auch keine neuen Tasmota Devices anlegen und hab eigentlich auch keine Lust auf MQTT2 umzustellen wenn es sonst bestens mit Mosquitto lief. Wäre schön wenn es einen Fix für das Modul "Tasmota Device" geben würde. Hab es jetzt erstmal direkt über die FHEM.cfg gemacht - aber das sollte eigentlich nicht die Regel werden ;-) .... Danke

**Comment by Raabensohn** [comment]
Fände auch cool, wenn das behoben würde.

**Comment by klein0r** [comment]
Sollte seit der letzten Version wieder klappen

**Comment by ManfredBrauchle** [comment]
morgen mal ausprobieren .. thumbs up schon mal :+1:

**Comment by ManfredBrauchle** [comment]
läuft .. danke 

:+1:
