### ISSUE TITLE
Built-In Taster von einem Sonoff in FHEM über MQQT auswerten.

### ISSUE THREAD

**Issue by StefTank** [klein0r/fhem-tasmota#21]
Hallo,
ich möchte den eingebauten Taster von einem Sonoff in FHEM über MQTT auswerten.
Den Ansatz, bei dem ich nicht weiter komme, geht über BottomTopic.

MQTT full topic	 ist /SmartHome/TestSonoff/cmnd/

Den ButtomTopic habe ich /TestSonoff/Taster genannt.
CMD: ButtonTopic
MQT: /SmartHome/TestSonoff/stat/RESULT = {"ButtonTopic":"/TestSonoff/Taster"}

Beim drücken des Tasters, wird am MQQT-Client folgendes ausgegeben:
/SmartHome/TestSonoff/Taster/cmnd/POWER	-->	TOGGLE

Mit /SmartHome/TestSonoff/cmnd/POWER -->on/off kann ich das Relais schalten.
Auch in FHEM kann ich schalten, Readings werden erzeugt.

Damit sollte ich alles haben was ich brauche, aber in FHEM wird beim drücken des Tasters kein Reading erzeugt.

Ziel ist über FHEM das Sonoffrelais über eine Logik zu schalten, die Logik aber zu verändern wenn der Taster am Sonoff gedrückt wird.

**Comment by klein0r** [comment]
Dazu kannst Du einfach ein zusätzliches subscribe Attribut anlegen. Also genau wie bei dem normalen MQTT-Device auch. Dann sollte es klappen
