### ISSUE TITLE
Undefined subroutine &JSON::decode_json 

### ISSUE THREAD

**Issue by tom2win** [klein0r/fhem-tasmota#3]
Habe es bereits mit "/" und ohne am ende probiert.

Bekomme die Readings leider nicht rein mit folgender FHEM Log Message:

bad JSON: status: {"Status":{"Module":6,"FriendlyName":"SO_3","Topic":"so_3","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}} - Undefined subroutine &JSON::decode_json called at ./FHEM/10_TASMOTA_DEVICE.pm line 233.

**Comment by 01findus** [comment]
Hallo Zusammen, habe das gleiche Problem:
TASMOTA POW Version 5.12.0 
FHEM: Latest Revision: 16206
Fehlermeldung:
2018.02.19 02:41:32 2: bad JSON: sensor: {"Time":"2018.02.19 02:41:31","ENERGY":{"Total":0.000,"Yesterday":0.000,"Today":0.000,"Period":0,"Power":0,"Factor":0.00,"Voltage":227,"Current":0.000}} - Undefined subroutine &JSON::decode_json called at ./FHEM/10_TASMOTA_DEVICE.pm line 243.

**Comment by klein0r** [comment]
Das json-Paket ist natürlich Voraussetzung 😄 

```
sudo apt-get install libjson-perl libjson-xs-perl
```
(ob man xs wirklich braucht weiß ich nicht, ich installiere das irgendwie immer mit)

**Comment by 01findus** [comment]
Danke das json Paket hatte ich schon installiert, das war bei mir nicht der Fix. Ich habe FHEM jetzt gerade die auf die neueste Version (508a248) Deines Moduls 10_TASMOTA_DEVICE.pm aktualisiert und voila alle readings sind da. TOP!
