### ISSUE TITLE
Device not running out-of-the-box

### ISSUE THREAD

**Issue by florie1706** [klein0r/fhem-tasmota#5]
Referring to https://github.com/klein0r/fhem-tasmota/issues/1 the TASMOTA_DEVICE just runs with certain conditions. Maybe there is a way to have any condition running.

First I need to have a / at the end of the full topic within the Sonoff.
Second I can't get the FHEM device running for the first time, so I need to edit the DEF in FHEM first and set it to the full topic without a / afterwards. When this is saved to fhem.cfg the device is running perfectly.

**Comment by klein0r** [comment]
Should be fixed
