### ISSUE TITLE
on-for-timer function needed

### ISSUE THREAD

**Issue by handy80** [klein0r/fhem-tasmota#6]
Hi, is it possible to add a function "on-for-timer" like integrated in switches of HomeMatic
like: set Tastmota_device on-for-timer 1800 (switch on for 1800 seconds)

**Comment by florie1706** [comment]
If so, please also add off-for-timer ;)

**Comment by Maergsche** [comment]
I need on-for-time and off-for-timer too...

Here is my current solution: 
{ fhem("set device_name Power on ;; define device_name_OFF at +00:00:10 set device_name Power off")}

**Comment by emhal** [comment]
check this thread in the FHEM forum. That is the solution that I'm currently using:
https://forum.fhem.de/index.php?topic=82240.0

**Comment by gbomacfly** [comment]
set extension support would be great :)

**Comment by klein0r** [comment]
Done 👍
